# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "GDG Francisco Beltrão"
email: "gdgfranciscobeltrao@gmail.com"
description: "O GDG Francisco Beltrão é uma comunidade focada em tecnologias Google"
baseurl: ""
url: "https://gdg-fb.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-71096222-1"
googleAnalyticsSiteUrl: "gdg-fb.github.io"

# Organizer Info
organizerName: "GDG Francisco Beltrão"
organizerAlternateName: "Google Developer Group Francisco Beltrão"
organizerDescription: "Uma comunidade aberta de geeks voluntários que criam projetos interessantes e compartilham experiências sobre as tecnologia do Google com paixão."
organizerEmail: "gdgfranciscobeltrao@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://gdg-fb.github.io/"

# Head
metaKeywords: "gdg, Francisco Beltrão, Beltrão, google, programming, android, chrome, developers, paraná, sudoeste"
twitterAccount: "@gdg_fb"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://goo.gl/forms/BjrVuXKCGV"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/team/", text: "Equipe"}
bottomNavigationLinks:
 - {link: "http://goo.gl/forms/BjrVuXKCGV", text: "Venha fazer parte!"}
rightNavigationButtons:
 - {link: "http://goo.gl/forms/BjrVuXKCGV", text: "Venha fazer parte!"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "GDG Francisco Beltrão é <typeout>"
eventDate: ""
typeoutTextValues: '"", "Tecnologia", "Comunidade", "Inspiração", "Design", "Transformação"'
typeoutFallback: "Transformação"
heroButtons:
 - {link: "http://goo.gl/forms/BjrVuXKCGV", text: "Venha fazer parte!"}

# About Block
aboutTitle: "O que é o GDG Francisco Beltrão?"
aboutBlock:
 - {title: "Meetups", image: "conference.jpg", text: "Palestras e networking sobre as principais tecnologias Google, com palestrantes especialistas e muita diversão" }
 - {title: "Workshops", image: "workshop.jpg", text: "Encontros e Fins de semana de aprendizado prático, mão na massa para fazer coisas legais e úteis" }
 - {title: "Hackathons", image: "hackathon.jpg", text: "Hackathons em parceria com as mais diversas instituições para transformar a nossa realidade com o uso da tecnologia!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "1534", specialCharacter: "+", info: "Participantes", detail: "de todo sudoeste!"}
 - {count: "10", specialCharacter: "+", info: "Eventos", detail: "de pura tecnologia!"}
 - {count: "9", specialCharacter: "+", info: "speakers", detail: "das mais diversas áreas"}
 - {count: "1", specialCharacter: "", info: "objetivo", detail: "Transformar Francisco Beltrão e região!"}

# Latest News Block
latestNewsTitle: "Destaques no blog!"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Quem torna isso possível?"
rockstarSpeakersButtonText: "Veja mais sobre a equipe"

# Location Block
locationBlockTitle: "Nossa casa"
eventLocationName: "CITFBE - Centro de Inovação e Tecnologia de Francisco Beltrão"
eventStreetAddress: "R. Ten. Camargo - Luther King,"
eventAddressLocality: "Francisco Beltrão"
eventAddressLocalityRegion: "PR"
eventPostalCode: "00"
eventAddressCountry: "Brasil"
eventStartTime: "2016-10-25T10:00"
eventDoorTime: "09:00"
eventEndTime: "2014-10-25T20:00"
eventPlaceCoordinates: "-26.069492, -53.043392"
mapCenterCoordinates: "-26.069492, -53.043392"
mapMobileCenterCoordinates: "-26.069492, -53.043392"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Kinopalace Cinema"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Siga-nos no twitter: "
twitterHashTag: "gdg_fb"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://plus.google.com/102178819169878551962", icon: "google-plus"}
 - {link: "https://twitter.com/gdg_fb", icon: "twitter"}
 - {link: "https://www.facebook.com/GDG-Francisco-Beltr%C3%A3o-449389415208060/?pnref=lhc", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://gdg0fb.github.io", text: "GDG FB"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:gdgfranciscobeltrao@gmail.com", text: "Nosso email."}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Código de Conduta"}

# Blog
blogTitle: "Blog"
blogCommentsEnabled: true
discusShortName: "gdgfb"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Sobre nós"
aboutUs: "As tecnologias Google se tornaram sinônimo de coisas simples. O Google está criando todos os dias novos produtos cujas inovações tecnológicas e industriais de TI são enormes. É difícil conhecer todas elas. É por isso que as pessoas começaram a se reunir em pequenos grupos locais e partilhar a sua experiência. Mais tarde, os seguintes grupos foram chamados de GDGs, ou grupos de desenvolvedores do Google. GDGs pode assumir muitas formas - a partir de apenas algumas pessoas se reunindo para assistir alguns vídeos, ou até mesmo grandes encontros com demonstrações, palestras técnicas, hackathons e conferências. DISCLAIMER: O GDG Fco. Beltrão é um grupo independente; nossas atividades e as opiniões aqui expressas não devem, de forma alguma, ser ligadas ao Google."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
